### ISSUE TITLE
Error when using with React

### ISSUE THREAD

**Issue by Epiczzor** [JamesLMilner/THREEAR#106]
Hey
So i am trying to make this work with my React and react-three-fiber project
i followed the repo you mentioned on #76 as [here](https://github.com/kalwalt/react-AR-experiments/tree/master/react-threear-example)

I get the following console logs
```
Allocated videoFrameSize 1228800
Pattern detection mode set to 1.
Pattern ratio size set to 0.500000.
```
And then I am getting the following error
`
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
`

I'm not sure where im wrong

**Comment by Epiczzor** [comment]
I solved this issue, it is not an error with THREEAR

the setup in the [repository](https://github.com/kalwalt/react-AR-experiments]) was incorrect, i had to initialize threear outside the render function, ill put up a repository shortly with a boiler plate of integrating this with React

**Comment by JamesLMilner** [comment]
Glad you managed to get it sorted!
