### ISSUE TITLE
Example links not working

### ISSUE THREAD

**Issue by dirkk0** [JamesLMilner/THREEAR#98]
Hi,

the
- Docs
- Examples (Source)
- Examples (Live)

point to https://jamesmilneruk.github.io/THREEAR/docs etc which don't seem to exist.

Best regards,
  Dirk

**Comment by JamesLMilner** [comment]
@dirkk0 yeah, that happened as I changed my GitHub handle and haven't had time to change the URLs. I will make a PR the next time I have availability.

**Comment by JamesLMilner** [comment]
This is fixed in #99
